name: Build RK3399 Device Tree

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dtb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu make device-tree-compiler

      - name: Clone Batocera from master branch
        run: |
          git clone --depth=1 --branch=master https://github.com/batocera-linux/batocera.linux.git batocera-source
          
          # 查看 Batocera 使用的内核版本
          cd batocera-source
          if [ -f "package/batocera/core/linux/linux-source/linux-version.inc" ]; then
            KERNEL_VERSION=$(grep -oP 'LINUX_VERSION\s*=\s*\K[0-9]+\.[0-9]+(\.[0-9]+)?' package/batocera/core/linux/linux-source/linux-version.inc)
          else
            # 如果找不到版本文件，使用默认版本
            KERNEL_VERSION="6.14.5"
          fi
          echo "Using kernel version: $KERNEL_VERSION"
          
          # 将内核版本保存到文件供后续步骤使用
          echo "KERNEL_VERSION=$KERNEL_VERSION" > ../kernel_version.txt
          
          cd ..
          
      - name: Clone Linux kernel
        run: |
          # 读取上一步保存的内核版本
          source kernel_version.txt
          echo "Cloning Linux kernel version $KERNEL_VERSION"
          
          # 获取适当的内核源代码
          git clone --depth=1 --branch=v${KERNEL_VERSION} https://github.com/torvalds/linux.git
          cd linux
          
          # 如果内核版本存在问题，尝试最新的稳定版
          if [ $? -ne 0 ]; then
            echo "Failed to clone specific kernel version, trying latest stable"
            cd ..
            git clone --depth=1 https://github.com/torvalds/linux.git
          fi
          
      - name: Copy custom DTS files
        run: |
          mkdir -p linux/arch/arm64/boot/dts/rockchip/
          cp rk3399-am40.dtsi linux/arch/arm64/boot/dts/rockchip/
          
          # 创建一个自定义 DTS 文件引用我们的 DTSI
          cat > linux/arch/arm64/boot/dts/rockchip/rk3399-am40.dts << 'EOL'
          /dts-v1/;
          #include "rk3399.dtsi"
          #include "rk3399-am40.dtsi"
          / {
              model = "AM40 (RK3399)";
              compatible = "rockchip,rk3399-am40", "rockchip,rk3399";
          };
          EOL
          
          # 修改 Makefile 添加我们的 DTS
          echo "dtb-\$(CONFIG_ARCH_ROCKCHIP) += rk3399-am40.dtb" >> linux/arch/arm64/boot/dts/rockchip/Makefile

      - name: Compile device tree
        run: |
          cd linux
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dtbs
          
      - name: Upload DTB
        uses: actions/upload-artifact@v4
        with:
          name: rk3399-am40-dtb
          path: linux/arch/arm64/boot/dts/rockchip/rk3399-am40.dtb
          
      - name: Summary
        run: |
          source kernel_version.txt
          echo "## 构建摘要" >> $GITHUB_STEP_SUMMARY
          echo "- 使用的 Batocera 分支: master" >> $GITHUB_STEP_SUMMARY
          echo "- 使用的 Linux 内核版本: $KERNEL_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- 设备树文件已成功编译并上传为工件" >> $GITHUB_STEP_SUMMARY
          echo "- 您可以下载 rk3399-am40.dtb 并与 Batocera 镜像一起使用" >> $GITHUB_STEP_SUMMARY
