name: Build 32bit musl static (sqlite)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 编译 Alist：32位 musl + sqlite3 静态
      - name: Build Alist 386
        uses: docker/build-push-action@v6
        with:
          context: .
          file: -
          platforms: linux/386
          outputs: type=local,dest=./out
          build-args: |
            REPO=https://github.com/AlistGo/alist.git
          dockerfile: |
            FROM i386/alpine:3.19
            RUN apk add --no-cache gcc musl-dev git go
            ARG REPO
            RUN git clone --depth=1 $REPO /build
            WORKDIR /build
            RUN CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -o alist -tags sqlite3 -ldflags "-w -s -extldflags '-static'"
            ENTRYPOINT ["/bin/sh"]

      # 编译 V2Ray：32位 静态
      - name: Build V2Ray 386
        uses: docker/build-push-action@v6
        with:
          context: .
          file: -
          platforms: linux/386
          outputs: type=local,dest=./out
          build-args: |
            REPO=https://github.com/v2fly/v2ray-core.git
          dockerfile: |
            FROM i386/alpine:3.19
            RUN apk add --no-cache git go
            ARG REPO
            RUN git clone --depth=1 $REPO /build
            WORKDIR /build
            RUN CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o v2ray -ldflags "-w -s" ./main
            ENTRYPOINT ["/bin/sh"]

      # 上传最终产物
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-386-musl-static-sqlite
          path: |
            out/alist
            out/v2ray
